development:
  adapter: postgresql
  encoding: unicode
  database: ember-hello-world_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ember-hello-world_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ember-hello-world_production
  pool: 5
